package org.platform.snail.model;

import java.util.Date;

public class Department implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.DEPARTMENT_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String departmentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.PARENT_DEPARTMENT_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String parentDepartmentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.DEPARTMENT_NAME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String departmentName;

	private String describtion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.DEPARTMENT_LEVEL
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String departmentLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.USER_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.CREATE_TIME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.CREATE_USER_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column DEPARTMENT.STATUS
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String status;

	private String childCount;

	private String hourceNumber;

	private String areaCode;
	private String areaName;
	private String p_code;// 首字母

	public String getP_code() {
		return p_code;
	}

	public void setP_code(String p_code) {
		this.p_code = p_code;
	}

	public String getChildCount() {
		return childCount;
	}

	public void setChildCount(String childCount) {
		this.childCount = childCount;
	}

	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId == null ? null : departmentId.trim();
	}

	public String getParentDepartmentId() {
		return parentDepartmentId;
	}

	public void setParentDepartmentId(String parentDepartmentId) {
		this.parentDepartmentId = parentDepartmentId == null ? null : parentDepartmentId.trim();
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	public String getDepartmentLevel() {
		return departmentLevel;
	}

	public void setDepartmentLevel(String departmentLevel) {
		this.departmentLevel = departmentLevel;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	public String getDescribtion() {
		return describtion;
	}

	public void setDescribtion(String describtion) {
		this.describtion = describtion;
	}

	public String getHourceNumber() {
		return hourceNumber;
	}

	public void setHourceNumber(String hourceNumber) {
		this.hourceNumber = hourceNumber;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Override
	public String toString() {
		return "Department [departmentId=" + departmentId + ", parentDepartmentId=" + parentDepartmentId
				+ ", departmentName=" + departmentName + ", describtion=" + describtion + ", departmentLevel="
				+ departmentLevel + ", userId=" + userId + ", createTime=" + createTime + ", createUserId="
				+ createUserId + ", status=" + status + ", childCount=" + childCount + ", hourceNumber=" + hourceNumber
				+ "]";
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

}
